_merge: deep
page:
  articles:    /nos-articles/:slug/
  casestudies: /etudes-de-cas/:slug/
  services:    /nos-expertises/:slug/
section:
  articles:    /nos-articles/
  casestudies: /etudes-de-cas/
  services:    /nos-expertises/
